# Generated by Django 3.2.8 on 2021-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registro_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
